---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - .root.app.yaml
  - ../../apps/mu

patches:
  - path: mu.app.yaml
    target:
      kind: Application
      name: mu
      namespace: argocd
