---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../appsets/example

patches:
  - path: patches/example.appset.yaml
    target:
      kind: ApplicationSet
      group: argoproj.io
      version: v1alpha1
      name: example
      namespace: argocd
