---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example

resources:
  - ../../base

helmCharts:
  - name: app
    repo: oci://public.ecr.aws/andreswebs/charts
    version: 0.0.1
    namespace: example
    releaseName: nu
    valuesFile: ../../base/nu.helm.values.yaml
    additionalValuesFiles:
      - nu.helm.values.yaml
