---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: mu
spec:
  project: workloads

  sources:
    - repoURL: https://github.com/andreswebs/argo-example-k8s-config.git
      chart: charts/mu
      targetRevision: 0.0.0 # set on overlay
      helm:
        valueFiles:
          - $cluster/mu.helm.values.yaml

    - repoURL: https://github.com/andreswebs/argo-example-k8s-config.git
      targetRevision: main
      ref: cluster
      path: "" # set on overlay to clusters/<cluster>

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - Replace=true
      - ApplyOutOfSyncOnly=true
