---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [missingkey=error]
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: '{{ dig "wave" "100" . }}'
    spec:
      project: example

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
          - ServerSideApply={{ dig "syncServerSideApply" "false" . }}
        automated:
          prune: true
          selfHeal: true

      source:
        repoURL: ssh://git@github.com/Workplace-Engagement/k8s-example
        targetRevision: main
        path: "{{ .path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
