---
name: Inspect
on:
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Inspect
        run: |
          helm dependency build clusters/sandbox/apps/mu
          helm template --debug clusters/sandbox/apps/mu | tee mu.sandbox.source.yaml
