---
name: Pull Request
on:
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clusters:
          - sandbox
        charts:
          - mu
          - nu
          - tu

    env:
      CLUSTER: ${{ matrix.clusters }}
      CHART_NAME: ${{ matrix.charts }}
      APP_PATH: ./clusters/${{ matrix.clusters }}/apps/${{ matrix.charts }}
      APP_ID: ${{ matrix.charts }}.${{ matrix.clusters }}
      SOURCE_YAML: ${{ matrix.charts }}.${{ matrix.clusters }}.source.yaml
      SOURCE_ARTIFACT: ${{ matrix.charts }}-${{ matrix.clusters }}-source
      TARGET_YAML: ${{ matrix.charts }}.${{ matrix.clusters }}.target.yaml
      TARGET_ARTIFACT: ${{ matrix.charts }}-${{ matrix.clusters }}-target

    steps:
      - name: Environment
        env:
          APP_PATH: ${{ env.APP_PATH }}
          APP_ID: ${{ env.APP_ID }}
          SOURCE_YAML: ${{ env.SOURCE_YAML }}
          TARGET_YAML: ${{ env.TARGET_YAML }}
        run: |
          echo "APP_PATH=${APP_PATH}" >> $GITHUB_ENV
          echo "APP_ID=${APP_ID}" >> $GITHUB_ENV
          echo "SOURCE_YAML=${SOURCE_YAML}" >> $GITHUB_ENV
          echo "TARGET_YAML=${TARGET_YAML}" >> $GITHUB_ENV

      - name: Inspect
        run: |
          helm version
