---
name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  diff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clusters:
          - sandbox
        charts:
          - mu
          - nu
          - tu

    env:
      CLUSTER: ${{ matrix.clusters }}
      CHART_NAME: ${{ matrix.charts }}
      APP_PATH: ./clusters/${{ matrix.clusters }}/apps/${{ matrix.charts }}
      APP_ID: ${{ matrix.charts }}.${{ matrix.clusters }}
      SOURCE_YAML: ${{ matrix.charts }}.${{ matrix.clusters }}.source.yaml
      SOURCE_ARTIFACT: ${{ matrix.charts }}-${{ matrix.clusters }}-source
      TARGET_YAML: ${{ matrix.charts }}.${{ matrix.clusters }}.target.yaml
      TARGET_ARTIFACT: ${{ matrix.charts }}-${{ matrix.clusters }}-target

    steps:
      - name: Environment
        env:
          APP_PATH: ${{ env.APP_PATH }}
          APP_ID: ${{ env.APP_ID }}
          SOURCE_YAML: ${{ env.SOURCE_YAML }}
          TARGET_YAML: ${{ env.TARGET_YAML }}
        run: |
          echo "APP_PATH=${APP_PATH}" >> $GITHUB_ENV
          echo "APP_ID=${APP_ID}" >> $GITHUB_ENV
          echo "SOURCE_YAML=${SOURCE_YAML}" >> $GITHUB_ENV
          echo "TARGET_YAML=${TARGET_YAML}" >> $GITHUB_ENV

      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Source Template
        run: |
          helm dependency build "${APP_PATH}"
          helm template "${APP_PATH}" | tee "${SOURCE_YAML}"

      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SOURCE_ARTIFACT }}
          path: ${{ env.SOURCE_YAML }}

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Download source artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.charts }}-${{ matrix.clusters }}-source

      - name: Target Template
        run: |
          helm dependency build "${APP_PATH}"
          helm template "${APP_PATH}" | tee "${TARGET_YAML}"

      - name: Upload target artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET_ARTIFACT }}
          path: ${{ env.TARGET_YAML }}

      - name: Diff
        run: |
          diff ${SOURCE_YAML} ${TARGET_YAML} | tee ${APP_ID}.diff.txt

      - name: Report
        uses: andreswebs/gh-actions/.github/actions/file-report@main
        with:
          source-txt-file: ${APP_ID}.diff.txt
          environment: ${{ env.CLUSTER }} - ${{ env.CHART }}
